### PR TITLE
Remove Hashing From Service Endpoints

### LINKED ISSUE #719: Updating azuredevops_serviceendpoint_dockerregistry description resets password
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azuredevops_serviceendpoint_dockerregistry`
* `azuredevops_serviceendpoint_artifactory`
* probably more

### Expected Behavior

Updating the service connection description should not affect the password.

### Actual Behavior

Updating the service connection description broke all our pipelines using this resource.

### Important Factoids

I'm pretty sure this affects quite a few resources. Need to confirm that with some more testing. The Artifactory resource has an [attempted workaround](https://github.com/microsoft/terraform-provider-azuredevops/blob/main/azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_artifactory.go#L121) which I confirmed is broken. The "null" trick didn't work at all in my testing.

### PR DESCRIPTION
**Pull request by davidcorrigan714**
## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [ ] My code follows the code style of this project.
* [x] I ran lint checks locally prior to submission.
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

This PR removes hashing of sensitive data from all the service connection resources to resolve #719 #692 #719 #732 #629 . While I applaud the effort to protect sensitive data, it was very buggy and I'm not at all confident all those issues are resolvable while maintaining the hashing. Hopefully Hashicorp has a standard solution at some point, [see this issue](https://github.com/hashicorp/terraform/issues/516). I also reviewed the handling of all service connection fields marked as sensitive in ADO to make sure they're never read back into the state file.

Note that this may unmask sensitive data currently stored in state by service connection resources - though when cleaning this up it was more inconsistently applied than I thought. I can find no mention in the documentation that this provider attempts to protect sensitive data, though many providers have an explicit warning that they will store sensitive data in plain text in state files. [Example](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_secret). [Hashicorp provides guidance to users to secure state](https://developer.hashicorp.com/terraform/plugin/best-practices/sensitive-state) so I'm 50/50 on whether the warning text should be added to every service connection doc page.

Note that acceptance tests cannot currently cover all the instances of bugs this fixes. I wrote a custom task extension to write sensitive service connection out to pipeline logs in plain text to debug and validate a lot of the updates. It'd be nice to incorporate that into the acceptance tests, but that's quite the undertaking and the current ADO Go API may not even have all the necessary hooks, on top of needing to publish an extension to retrieve the protected data.

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [x] No

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by davidcorrigan714** [comment]
Well I ran the linting and formatting checks, can't say the output was exactly clean. gofmt apparently doesn't play nice with windows line endings and the linter is complaining about vendoring which I don't think I changed with this.

**Comment by xuzhang3** [comment]
@davidcorrigan714 would you mind if I directly push changes to this PR to fix the CI errors?

**Comment by xuzhang3** [comment]
> Well I ran the linting and formatting checks, can't say the output was exactly clean. gofmt apparently doesn't play nice with windows line endings and the linter is complaining about vendoring which I don't think I changed with this.

I normally  set `git config`  `core.autocrlf=true`  to ensure line ending will automatically  formatted across platforms.

**Comment by davidcorrigan714** [comment]
Have at it, going to be a little while before I have time to do any updates
myself.

**Comment by xuzhang3** [comment]
> 

Can you give me the push permissions? I cannot push to this PR.

**Comment by davidcorrigan714** [comment]
[Apparently](https://github.com/orgs/community/discussions/5634) I don't have that option since my PR is from an organization account. Not sure what the cleanest way is to get it out of that account, doesn't look easy to just give you access to that specific branch on our fork either.

**Comment by davidcorrigan714** [comment]
Suppose I can fork the fork into my personal account and submit a new PR. It's not like there's been much happening on this one. Or you're free to sync it and do a new PR from another account, doesn't bother me at all if this code ends up officially coming from my account or a PR directly from me.

**Comment by xuzhang3** [comment]
@davidcorrigan714 closing this PR as the changes has been merged by #856

**Pull request merged**
