### PR TITLE
PowerShell scripts

### PR DESCRIPTION
**Pull request by tmeckel**
## All Submissions:

* [YES] Have you added an explanation of what your changes do and why you'd like us to include them?
* [YES] I have updated the documentation accordingly.
* [NA] I have added tests to cover my changes.
* [NA] All new and existing tests passed.
* [NA] My code follows the code style of this project.
* [NA] I ran lint checks locally prior to submission.
* [YES] Have you checked to ensure there aren't other open PRs for the same update/change?

## What is the current behavior?

The current repository provides no scripts to build the Azure DevOps Terraform  provider on Windows.

## What is the new behavior?

This PR provides a couple of Powershell scripts to build the provider on any platform where Powershell and Go are supported. 

In addition the link to the Gitter channel for the provider has been added README.md again.

## Does this introduce a breaking change?

- [NO]

## Any relevant logs, error output, etc?

[N/A]

### CODE REVIEW

**Comment by nmiodice** [comment]
@tmeckel is this still a draft?

**Comment by tmeckel** [comment]
@nmiodice well there should be some sort of documentation ... right? :grin: and according to the review of @cgriggs01 form Hashicorp we should (have to?) replace the scripts anyway #242. So I doubt in the light of this review my contribution of the Powershell scripts make still any sense.

**Comment by nmiodice** [comment]
@tmeckel, I agree. Lets close this out and re-visit if we find the Powershell scripts to be necessary in the future.

**Comment by tmeckel** [comment]
@nmiodice just a bit __toooo__ quick now 😁 I have a project in which we might have to build, install and use the provider under Windows. So the Powershell scripts would really help. I don't have the `reopen` button available. Can you reopen the PR please?

**Comment by nmiodice** [comment]
@tmeckel - done :). Please drop a note when not in WIP mode and I'll happily take a look

**Comment by tmeckel** [comment]
@nmiodice thanks for quickly reopening the PR!!

**Comment by tmeckel** [comment]
@nmiodice Nick! I finally found some time to finalize the PR. Requesting a review.

**Comment by nmiodice** [comment]
```
 ____   _____        _______ ____  ____  _   _ _____ _     _
|  _ \ / _ \ \      / / ____|  _ \/ ___|| | | | ____| |   | |
| |_) | | | \ \ /\ / /|  _| | |_) \___ \| |_| |  _| | |   | |
|  __/| |_| |\ V  V / | |___|  _ < ___) |  _  | |___| |___| |___
|_|    \___/  \_/\_/  |_____|_| \_\____/|_| |_|_____|_____|_____|
```

**Comment by tmeckel** [comment]
> ```
>  ____   _____        _______ ____  ____  _   _ _____ _     _
> |  _ \ / _ \ \      / / ____|  _ \/ ___|| | | | ____| |   | |
> | |_) | | | \ \ /\ / /|  _| | |_) \___ \| |_| |  _| | |   | |
> |  __/| |_| |\ V  V / | |___|  _ < ___) |  _  | |___| |___| |___
> |_|    \___/  \_/\_/  |_____|_| \_\____/|_| |_|_____|_____|_____|
> ```

@nmiodice  YEEEEEHAAAAAWWW 😁 finally no more fiddling around with git stashes anymore for me on Windows!

**Pull request merged**
