### PR TITLE
Don't set `azuredevops_serviceendpoint_generic` and `azuredevops_serviceendpoint_bitbucket`  password to empty string

### PR DESCRIPTION
**Pull request by xuzhang3**
## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran lint checks locally prior to submission.
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Service endpoint sensitive data won't returned by service,  local config should not be changed based on  service repsonse
Issue Number: #550

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [x] No

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

### CODE REVIEW

**Comment by xuzhang3** [comment]
AccTest:
```
=== RUN   TestAccServiceEndpointGeneric_basic
=== PAUSE TestAccServiceEndpointGeneric_basic
=== RUN   TestAccServiceEndpointGeneric_complete
=== PAUSE TestAccServiceEndpointGeneric_complete
=== RUN   TestAccServiceEndpointGeneric_update
=== PAUSE TestAccServiceEndpointGeneric_update
=== RUN   TestAccServiceEndpointGeneric_RequiresImportErrorStep
=== PAUSE TestAccServiceEndpointGeneric_RequiresImportErrorStep
=== CONT  TestAccServiceEndpointGeneric_basic
=== CONT  TestAccServiceEndpointGeneric_update
=== CONT  TestAccServiceEndpointGeneric_complete
=== CONT  TestAccServiceEndpointGeneric_RequiresImportErrorStep
--- PASS: TestAccServiceEndpointGeneric_complete (113.62s)
--- PASS: TestAccServiceEndpointGeneric_update (192.50s)
--- PASS: TestAccServiceEndpointGeneric_basic (209.99s)
--- PASS: TestAccServiceEndpointGeneric_RequiresImportErrorStep (347.01s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests        348.718s

=== RUN   TestAccServiceEndpointBitBucket_basic
=== PAUSE TestAccServiceEndpointBitBucket_basic
=== RUN   TestAccServiceEndpointBitBucket_complete
=== PAUSE TestAccServiceEndpointBitBucket_complete
=== RUN   TestAccServiceEndpointBitBucket_update
=== PAUSE TestAccServiceEndpointBitBucket_update
=== RUN   TestAccServiceEndpointBitBucket_RequiresImportErrorStep
=== PAUSE TestAccServiceEndpointBitBucket_RequiresImportErrorStep
=== CONT  TestAccServiceEndpointBitBucket_basic
=== CONT  TestAccServiceEndpointBitBucket_RequiresImportErrorStep
=== CONT  TestAccServiceEndpointBitBucket_update
=== CONT  TestAccServiceEndpointBitBucket_complete
--- PASS: TestAccServiceEndpointBitBucket_complete (216.22s)
--- PASS: TestAccServiceEndpointBitBucket_basic (249.14s)
--- PASS: TestAccServiceEndpointBitBucket_update (277.25s)
--- PASS: TestAccServiceEndpointBitBucket_RequiresImportErrorStep (294.52s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests        295.850s


```

**Comment by SimonAlling** [comment]
Title sounds like an issue, not a PR/commit, to me. May I suggest this instead:

> Don't set `azuredevops_serviceendpoint_generic` password to empty string

**Comment by SimonAlling** [comment]
Also, I just noticed that this PR affects not only `azuredevops_serviceendpoint_generic`, but also `azuredevops_serviceendpoint_bitbucket`.

**Comment by xuzhang3** [comment]
@SimonAlling I checked similar resource `azuredevops_serviceendpoint_bitbucket` also have this issue, second apply will update the password/pat

**Comment by lindhe** [comment]
> I checked similar resource `azuredevops_serviceendpoint_bitbucket` also have this issue, second apply will update the password/pat

The title makes it sound like `azuredevops_serviceendpoint_bitbucket` is not part of this PR. That will make it harder to debug in the future; if there's something up with `azuredevops_serviceendpoint_bitbucket` it will be harder to find this commit that introduces changes  there. Oh well.

**Comment by xuzhang3** [comment]
@lindhe Personally I'd like debug source code if I have questions. The PR title won't bother me too much.  But you are right, commit/PR should represent for what the code changes, the log should be traceable.

**Pull request merged**
