### PR TITLE
Upgrade to v6 API

### PR DESCRIPTION
**Pull request by tmeckel**
## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] ~~I have updated the documentation accordingly.~~
* [ ] ~~I have added tests to cover my changes.~~
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran lint checks locally prior to submission.
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Issue Number: #204 #143 #491

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [x] Yes
- [ ] No

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

### CODE REVIEW

**Comment by tmeckel** [comment]
@nechvatalp I successfully migrated the provider to the v6 API. 

One **major issue** though: it is impossible to set a description for a Service Endpoint using [ServiceEndpointClient.CreateServiceEndpoint](https://docs.microsoft.com/en-us/rest/api/azure/devops/serviceendpoint/endpoints/create?view=azure-devops-rest-6.0)!

I verified this behavior using a Python script which utilizes the v6 Python API:

```Python
credentials = BasicAuthentication('', personal_access_token)
connection = Connection(base_url=organization_url, creds=credentials)

cc: Type[CoreClient]
cc = connection.clients_v6_0.get_core_client()
prj: Type[TeamProject]
prj = cc.get_project("Test Project")

spc: Type[ServiceEndpointClient]
spc = connection.clients_v6_0.get_service_endpoint_client()

ep_name = "Generic (TEST)"
ep = ServiceEndpoint(
    name=ep_name,
    description="Test description",
    type="generic",
    url="https://void.example.com",
    authorization=EndpointAuthorization(
        parameters={
            "username": "test",
            "password": "test"
        },
        scheme="UsernamePassword"),
    service_endpoint_project_references=[
        ServiceEndpointProjectReference(
            project_reference=ProjectReference(
                id=prj.id
            ),
            name=ep_name
        )
    ])

response = spc.create_service_endpoint(ep)
```

The description got passed via the `POST` Request to the API, but never got set. This can be easily verified by selecting the service endpoint of the corresponding project in the web interface. 

image

This behavior will always create a DIFF in Terraform because the `description` attribute is always empty.

We have three options here:

1. Staying with v5.1 API for the Service Endpoint. Definitely not my favorite because personally I really don't like a mixture of APIs inside such a project like the provider.
2. Ignoring changes on the description property entirely. 

    image

    Likewise with the v5.1 API not a great option, because this would be a step back for the functionality of the provider.
3. Removing the description property for a Service Endpoint in the provider. I think the worst option because this would be a breaking change for everyone who use the provider for managing Service Endpoints.
4. Get the v6 API fixed 😁 My favorite solution!!!!!

@xuzhang3 what's you opinion on this?

**Comment by favoretti** [comment]
Hey @tmeckel. Am I reading this wrong? https://github.com/microsoft/azure-devops-go-api/blob/0974d0145be828d8e35ef1b06a542e00938713ce/azuredevops/v6/serviceendpoint/models.go#L432

The ServiceEndpoint object does have a Description property...

**Comment by favoretti** [comment]
@nechvatalp On thing I'm pondering though.. Why does this SDK use `6.0-preview.4` instead of 6.1 which seems to be used everywhere else?

**Comment by roryprimrose** [comment]
@tmeckel The api model is a bit of a misdirect in this case. I find the easiest way to verify behaviour is to watch the browser traffic when the UI makes the change. Unfortunately the UI often does not use the formal API but in this case it does. The answer here is that the description property on the root object is not what you want to use.

image

image

The description in the UI is pushed into the object in the `serviceEndpointProjectReferences` array.

image

**Comment by xuzhang3** [comment]
@tmeckel   I prefer  options 4. This is a feature in UI, API should not breaking this experience.
@roryprimrose   You are right, UI use API v`6.0-preview.4`  and the description has been wrapped in the `serviceEndpointProjectReferences`. This should be a breaking between v5 and v6.

**Comment by tmeckel** [comment]
> @tmeckel The api model is a bit of a misdirect in this case. I find the easiest way to verify behaviour is to watch the browser traffic when the UI makes the change. Unfortunately the UI often does not use the formal API but in this case it does. The answer here is that the description property on the root object is not what you want to use.
> ...
> The description in the UI is pushed into the object in the `serviceEndpointProjectReferences` array.

@roryprimrose great catch! 👍🏼 I'll update the code accordingly.

**Comment by tmeckel** [comment]
@xuzhang3 I consider this PR ready to be merged. I ran a couple of acceptance tests, especially for the Service Endpoints and the changed implementation for the User Entitlement resource

image

image

image

**Comment by xuzhang3** [comment]
LGTM, shipping it

**Pull request merged**
