### PR TITLE
Update azure-devops-go-api to v1.0.0-b2

### PR DESCRIPTION
**Pull request by tmeckel**
## All Submissions:

* [YES] Have you added an explanation of what your changes do and why you'd like us to include them?
* [NA] I have updated the documentation accordingly.
* [NA] I have added tests to cover my changes.
* [NA] All new and existing tests passed.
* [NA] My code follows the code style of this project.
* [NA] I ran lint checks locally prior to submission.
* [YES] Have you checked to ensure there aren't other open PRs for the same update/change?

## What is the current behavior?

The current master branch uses an outdated version of the Azure DevOps GO API

## What is the new behavior?

The used version of the Azure DevOps GO API has been updated in `go.mod` and the `vendor` branch to [`v1.0.0-b2`](https://github.com/microsoft/azure-devops-go-api/releases/tag/azuredevops%2Fv1.0.0-b2)

## Does this introduce a breaking change?

- [NO]

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

N/A

## Other information

N/A

### CODE REVIEW

**Comment by tmeckel** [comment]
@nmiodice , @EliiseS , @xuzhang3 @tedchamb is again working on the DevOps GO API, and he just bumped the version to  [`1.0.0-b3`](https://github.com/microsoft/azure-devops-go-api/pull/73#event-3351800557). So perhaps we should wait merging the PR into master, because then I could update the referenced version again. Your thoughts?

**Comment by EliiseS** [comment]
We can merge this one and make a new one for b3 just as well. You'd have to remake all the changes pretty much, no? I'll be here to approve the next one too :D

**Comment by tmeckel** [comment]
Okay then let's go with the b2 version 😁

**Comment by tmeckel** [comment]
@EliiseS perhaps we should go with b3 because it should close the issue that prevented you from implementingsupport for using the keyvault with a variable group 😁  https://github.com/microsoft/azure-devops-go-api/issues/58

**Comment by tmeckel** [comment]
@EliiseS ooops 😁 b3 might not be such a great idea
image

**Comment by EliiseS** [comment]
Yeah, the changes for b3 are breaking changes for our code :P 
We need to fix them when we update.

Is b3 available now? I don't see a release yet. 

I keep my vote that we merge this and do b3 in a different PR.

**Comment by tmeckel** [comment]
@EliiseS there you go => https://github.com/microsoft/azure-devops-go-api/releases/tag/azuredevops%2Fv1.0.0-b3

**Comment by EliiseS** [comment]
@tmeckel B3 is broken, right? We can't upgrade to it?

**Comment by tmeckel** [comment]
@EliiseS B3 is not broken, but the implementation in `resource_variable_group.go` won't compile anymore, when we upgrade to B3 => (https://github.com/microsoft/terraform-provider-azuredevops/pull/327#issuecomment-630839579) 

So from my point of view, we can upgrade to B3 when we fix the code inside `resource_variable_group.go` in one single PR.

**Comment by EliiseS** [comment]
Right, of course! I forgot about that :P I'll upgrade in my PR

**Comment by tmeckel** [comment]
I am convinced that there are far too few emojis to choose from, to react to a comment 😁

**Comment by EliiseS** [comment]
How do we update the vendor files after updating the package version? Is there any documentation on that?

**Comment by xuzhang3** [comment]
> How do we update the vendor files after updating the package version? Is there any documentation on that?
@EliiseS
`go mod vendor` and `go mod tidy`

**Comment by EliiseS** [comment]
Thanks @xuzhang3!

**Pull request merged**
