### PR TITLE
Fix bug remove user and some improvements on membership

### PR DESCRIPTION
**Pull request by mikaelkrief**
## All Submissions:
-------------------------------------
* [YES] Have you added an explanation of what your changes do and why you'd like us to include them?
* [YES/NO] I have updated the documentation accordingly.
* [NA] I have added tests to cover my changes.
* [YES] All new and existing tests passed.
* [YES] My code follows the code style of this project.
* [YES] I ran lint checks locally prior to submission.
* [YES] Have you checked to ensure there aren't other open PRs for the same update/change?

## What is the current behavior?
-------------------------------------

It should be possible to modify the list memberships for a project in Azure DevOps. For example removing a user.

Issue Number: #188 

## What is the new behavior?
-------------------------------------
The bug to remove user is fixed
And probably also that fix the bug #174 

## Does this introduce a breaking change?
-------------------------------------
- [NO]

## Any relevant logs, error output, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

## Other information
-------------------------------------

### CODE REVIEW

**Comment by mikaelkrief** [comment]
@nmiodice , what is the bug ?

**Comment by nmiodice** [comment]
@mikaelkrief can you help me understand what the root cause of the following items are, and how this change fixes them?
 - The bug described in #188 
 - The transient failures for acceptance tests described in #174 ?

**Comment by mikaelkrief** [comment]
For #188 , I fixed the the method "ToStringSet" https://github.com/microsoft/terraform-provider-azuredevops/pull/212/files#diff-65b0b2389d375294824b22b5a2b143b1R120  in which there was a problem with object conversion.
I also readjusted the unit tests of this method.

For #174, there may have been a link between the 2 errors, I also added more control on the if statement https://github.com/microsoft/terraform-provider-azuredevops/pull/212/files#diff-0b9e7499660dedc2a8510b19ff9cde82R276.
I rerun the tests several times and I didn't have any errors. To follow...

**Comment by nmiodice** [comment]
For #174 the issue I ran into was that the AzDO group membership APIs had a (sometimes long) delay. This would cause 2 error cases:

- An apply followed by a refresh (which the acceptance test framework published by HashiCorp does automatically) would sometimes report that a new user or removed user was not reflected by the state
- An `add` followed by a `remove` (which is done by us, as a followup to the first step) would sometimes not be registered, based on the delay in the back-end API

I'm hesitant to un-comment these tests as we still don't have a good way to work around both of these.

**Comment by mikaelkrief** [comment]
ok agree, I will re-comment this test

**Comment by mikaelkrief** [comment]
@nmiodice , on my latest commit, I added some improvements with:
- add sleep 10 sc after creation/update of the membership => that solve problem of delay of the membership creation and terraform return -> maybe that can solve the transient issue .....

- Call the read method at the end of create/update method , as mentionned in  the terraform doc :  https://www.terraform.io/docs/extend/writing-custom-providers.html#implement-create

- update the terraform sample for use for_each instead count

**Comment by mikaelkrief** [comment]
@nmiodice , any news ?

**Comment by nmiodice** [comment]
@mikaelkrief so sorry for the delay. Things have been a little hectic on my end. Trying to not let it impact the PR attention here. Sorry!

Having a look now. The code looks fantastic. I need to update the PAT that the test uses to run as it has since expired. I'll kick off another build after fixing, but pending that, this looks good 2 go!

**Pull request merged**
