### PR TITLE
Refactor acceptance tests

### PR DESCRIPTION
**Pull request by EliiseS**
## All Submissions:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [ ] All new and existing tests passed.
* [ ] My code follows the code style of this project.
* [ ] I ran lint checks locally prior to submission.
* [ ] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Change acceptance tests to run in parallel to reduce the time it takes to run all tests. Now takes 7 minutes! 😄 Down from 11 :)

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [x] No

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

### CODE REVIEW

**Review by tmeckel — CHANGES_REQUESTED** [review]
LGTM except that I think this has to be documented for contributors in `docs/testing.md`

**Comment by xuzhang3** [comment]
@EliiseS Encountered this error whiling running in parallel. Serial won't get this error. Looks like `azuredevops_user_entitlement` is shared in some test case.  
```
=== CONT  TestAccGitRepo_CreateAndUpdate
    TestAccBranchPolicyMinReviewers_CreateAndUpdate: testing.go:673: Step 0 error: After applying this step and refreshing, the plan was not empty:

        DIFF:

        CREATE: azuredevops_user_entitlement.user
          account_license_type: "" => "express"
          descriptor:           "" => "<computed>"
          id:                   "" => "<computed>"
          licensing_source:     "" => "account"
          origin:               "" => "<computed>"
          origin_id:            "" => "<computed>"
          principal_name:       "" => "foo@contoso.com"
```

**Comment by EliiseS** [comment]
I actually encountered that while running serially before

**Comment by EliiseS** [comment]
Closing this because @xuzhang3 is right, I didn't see it before, but the tests are much for flakey when parallel

**Pull request merged**
