### PR TITLE
Expose app id of the automatic generated SP for AzureRM service endpoint

### PR DESCRIPTION
**Pull request by mispencer**
## All Submissions:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [X] All new and existing tests passed.
* [X] My code follows the code style of this project.
* [X] I ran lint checks locally prior to submission.
* [X] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Expose the id of the automatic generated service principal for an AzureRM service endpoint. This is necessary to grant other roles or other such changes to the generated SP within the terraform module.

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [X] No

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by mispencer** [comment]
I am unsure on how to write tests for this. Any help would be appreciated with this.

**Comment by xuzhang3** [comment]
@mispencer

> [CLA assistant check](https://cla.opensource.microsoft.com/microsoft/terraform-provider-azuredevops?pullRequest=241)
> Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/terraform-provider-azuredevops?pullRequest=241) before we can accept your contribution.
> 
> ❌ mispencer [sign now](https://cla.opensource.microsoft.com/microsoft/terraform-provider-azuredevops?pullRequest=241)
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/terraform-provider-azuredevops?pullRequest=241) it.

@mispencer  You need sign the  Contributor License Agreement.    
Current service endpoint [commons.go](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/internal/service/serviceendpoint/commons.go) has a bug. After the creation finished, `create` function won't invoke the [`read` function to retrieve the real resource but use the data generated in the `create` function](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/internal/service/serviceendpoint/commons.go#L172),   the result will be that the `serviceprincipalid`  will always be an empty string. You can wait for my bug fix PR or you can fix it.

**Comment by xuzhang3** [comment]
Hi @mispencer  Please sign the  Contributor License Agreement then I can help merge you PR.
 [CLA assistant check](https://cla.opensource.microsoft.com/microsoft/terraform-provider-azuredevops?pullRequest=241) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/terraform-provider-azuredevops?pullRequest=241) before we can accept your contribution.<br/><br/>:x: mispencer [sign now](https://cla.opensource.microsoft.com/microsoft/terraform-provider-azuredevops?pullRequest=241)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/microsoft/terraform-provider-azuredevops?pullRequest=241) it.</sub>

**Comment by mispencer** [comment]
I am working on getting approved to sign.

**Comment by xuzhang3** [comment]
Hi @mispencer  I'm going close this PR,  this feature has been implemented in another PR #241

**Pull request closed without merging**
