### PR TITLE
Permission management

### LINKED ISSUE #104: Implement Terrafrom resource azuredevops_project_permissions
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a developer, I want the ability to manage the permissions of a project in
Azure DevOps. Thus a new Terraform resource shall be provided.

### New or Affected Resource(s)

* azuredevops_project_permissions

### Potential Terraform Configuration

```hcl

data "azuredevops_project" "project" {
   # Exports: id
   project_name = "Test Project"
}

data "azuredevops_user" "lookup-user" {
   principalname_name  = "TestUser@contoso.com"
}

resource "azuredevops_group" "project-group" {
    project_id = azuredevops_project.project.id
    name       = "Test Group"
}

resource "azuredevops_project_permissions" "perm-project-group" {
    # Security Namespace: 52d39943-cb85-4d7f-8fa8-c6baac873819

    # Build ACL token from project id (GUID) as follows
    # $PROJECT:vstfs:///Classification/TeamProject/<ProjectGUID>
    project_id = data.azuredevops_project.project.id

    principals = [
        data.azuredevops_user.lookup-user.id_descriptor
        azuredevops_group.project-group.id_descriptor
    ]

    permissions = {
        "Enumerate"            = "Allow"
        "Delete"               = "Deny"
        "Publish_test_results" = "NotSet"
    }
}

```
### Acceptance Criteria

[] Include Unit tests for the new operation 

[] Acceptance (integration) test to validate repo creation/modification, 
   following the patterns from the azuredevops_build_definition resource

### References

* #127
* #103
* #84 
* [Security REST Api](https://docs.microsoft.com/en-us/rest/api/azure/devops/security/?view=azure-devops-rest-5.1)
* https://github.com/microsoft/azure-devops-go-api/blob/dev/azuredevops/security/client.go
* [Query Security Namespaces and their definitions](https://docs.microsoft.com/en-us/rest/api/azure/devops/security/security%20namespaces/query?view=azure-devops-rest-5.1)

### LINKED ISSUE #153: Implement Terrafrom resource azuredevops_git_permissions
## Community Note

* Please vote on this issue by adding a 👍
  [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)
  to the original issue to help the community and maintainers prioritize this
  request
* Please do not leave "+1" or "me too" comments, they generate extra noise for
  issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull
  request, please leave a comment

## Description

As a developer, I want the ability to manage the permissions of all Git
repositories inside a project, a single Git Repository and a single branch
inside a Git repository in Azure DevOps. Thus a new Terraform resource shall be
provided.

The resource shall provide three attributes to define the scope on which the
permissions should be applied:

* `project_id` (required)
* `repository_id` (optional)
* `branch_id` (optional)

Logic:

1. to apply permissions to all Git repositories inside a project set `project_id`
2. to apply permissions to a specific Git repository inside a project set `project_id` and `repository_id`
3. to apply permissions to a branch inside a Git repository of a project set `project_id`, `repository_id` and `branch_id`

The resource shall issue an error if:

1. the `project_id` is not set
2. the `branch_id` is set without having set `repository_id`

### New or Affected Resource(s)

* azuredevops_git_permissions

### Potential Terraform Configuration

```hcl

data "azuredevops_project" "project" {
   # Exports: id
   project_name = "Test Project"
}

resource "azuredevops_group" "project-group" {
    # Exports: id, descriptor (Security Descriptor)
    project_id = data.azuredevops_project.project.id
    name       = "Test Group"
}

data "azuredevops_git_repository" "repo" {
    name = "RepoV2"
}

data "azuredevops_git_branch" "branch_foobar" {
    name          = "Foobar"
    repository_id = data.azuredevops_git_repository.repo.id
    # Id            = /refs/heads/6d0061007300740065007200
}

resource "azuredevops_git_permissions" "perm" {
    # Security Namespace: 2e9eb7ed-3c0a-47d4-87c1-0ffdd275fd87

    // Build ACL token from project id (GUID) as follows
    // repoV2/<projectGUID>/<repoGUID>/<branchGUID>
    project_id    = data.azuredevops_project.project.id
    repository_id = data.azuredevops_git_repository.repo.id
    branch_id     = data.azuredevops_git_branch.branch_foobar.id

    principals = [
        data.azuredevops_project_user.lookup-project-user.id_descriptor
        azuredevops_user.project-user.id_descriptor
        # id_descriptor returns the decoded descriptor value (identity descriptor)
        # id => aad.YmZhYmE4ZDUtZWMzZC03ZjIzLWE4NDktMDM3ZjEwMTEwNDZh
        # id_descriptor => Microsoft.IdentityModel.Claims.ClaimsIdentity;2eb07b91-f9f8-437b-a89e-59f55e565c11\\EE03B31@UNION-INVESTMENT.DE
        azuredevops_group.project-group.id_descriptor
    ]

    permissions = {
        "Administer"   = "Allow"
        "ForcePush"    = "Deny"
        "CreateBranch" = "NotSet"
    }

}

```

### Acceptance Criteria

[] Include Unit tests for the new operation 

[] Acceptance (integration) test to validate repo creation/modification, 
   following the patterns from the azuredevops_build_definition resource

### References

* #0000

### PR DESCRIPTION
**Pull request by tmeckel**
## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran lint checks locally prior to submission.
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Issue Number:

* Closes #104
* Closes #153

The current implementation of the provider does not support the management of permission for project and git repositories.

This PR provides an implementation for two new resources (`azuredevops_project_permissions`, `azuredevops_git_permissions`) as described in the issues mentioned above and provides a framework for an easy implementation for other permission related Terraform resources (Security Namespace). 

In addition the single-value data source `azuredevops_git_repository` has been added.

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

* [ ] Yes
* [x] No

## Does this introduce a breaking change?

* [ ] Yes
* [x] No

## Any relevant logs, error output, etc?

[N/A]

### CODE REVIEW

**Comment by tmeckel** [comment]
This PR cannot be merged until the bug about an invalid `struct` element https://github.com/microsoft/azure-devops-go-api/issues/47 in the DevOps Go API has been fixed. Mention @tedchamb for reference here.

**Comment by tmeckel** [comment]
@nmiodice Nick can you ask @tedchamb when the above mentioned bug in the GO API will finally being fixed? We can not support any permission related stuff in the provider as long as that bug is not fixed. I know that @tedchamb has a new job, but nevertheless the situation around this little (but nasty) bug is getting somewhat ridiculous. @exocom @xuzhang3

**Comment by nmiodice** [comment]
@tmeckel I'm working on it through internal channels right now.

**Comment by tmeckel** [comment]
@nmiodice , @xuzhang3 Any information why the build pipeline failed?

**Comment by tmeckel** [comment]
@nmiodice , @xuzhang3 Guys the PR is finally ready for review. Too bad the pipeline failed, although I verified that the relevant acceptance, unit and linting tests were successful locally. So my usual question: any details from the pipeline why it failed?

**Comment by tmeckel** [comment]
@exocom Hey Kalarrs, if you find some time for a review, aside @nmiodice and @xuzhang3, I'd be happy!

**Comment by xuzhang3** [comment]
Hi @tmeckel  Pipeline AccTests failed. 
```
2020-06-12T14:43:45.3293539Z --- FAIL: TestAccProjectFeatures_EnableUpdateFeature (18.75s)
2020-06-12T14:43:45.3294506Z     testing.go:673: Step 0 error: Check failed: Check 2/2 error: azuredevops_project_features.project-features: Attribute 'features.artifacts' expected "disabled", got "enabled"
```

**Comment by tmeckel** [comment]
> TestAccProjectFeatures_EnableUpdateFeature

@xuzhang3 I'm wondering why this acceptance test fails because first off it passes and my side when I run it locally. 

image

and secondly because the error message makes little sense according to the design of the test. In both steps it's required that the `artifacts` feature is disabled and the HCL is _static_ on that property i.e. it doesn't chance between the two steps. Only the status of the `testplans` feature is switched between the steps.

So I suspect that the test fails either because it was a transient error, what is definitely likely since the test was added to the code base by my last PR #292 and on that PR the test didn't fail. Or we have this issue again that we're running the acceptance test(s) against the "special" Microsoft AzureDevOps organization which behaves different than the official customer organizations.

Anyway, could someone restart the pipeline of this PR, so that we can sort out a transient error?

Copy @nmiodice and @EliiseS

**Comment by xuzhang3** [comment]
Hi @tmeckel I re-run the failed pipeline and it is correct now. The failed pipeline was run last week.

**Comment by tmeckel** [comment]
> 
> 
> Hi @tmeckel I re-run the failed pipeline and it is correct now. The failed pipeline was run last week.

@xuzhang3 Awesome! Who will do the review then? I personally can't request a review because I'm only a contributor.

**Comment by xuzhang3** [comment]
Hi @tmeckel Sorry for inform late. This repository will migrate to Hashicorp official repo this week, we will freeze the code repo until migration finished (bug fix can be merged). But I will review the PR.

**Comment by tiwood** [comment]
@xuzhang3, I have a few PRs ready which requires this PR merged.
Do you have any plans to merge this short term? Do you plan to merge this here or in the new repo?

**Comment by xuzhang3** [comment]
@tiwood  Sorry for reply late. New features will be merged to new repository. Can you resubmit you PR to the new repository.

**Comment by tmeckel** [comment]
@xuzhang3 I filed a new PR https://github.com/terraform-providers/terraform-provider-azuredevops/pull/18

Closing this one.

Could you please archive this repository so that people can't file any additional issues and pull requests here.

**Pull request closed without merging**
