### PR TITLE
Adding release client so that release pipeline can be added.

### PR DESCRIPTION
**Pull request by exocom**
## All Submissions:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [N/A] I have updated the documentation accordingly.
* [N/A] I have added tests to cover my changes.
* [N/A] All new and existing tests passed.
* [X] My code follows the code style of this project.
* [X] I ran lint checks locally prior to submission.
* [X] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

No changes, this is adding the client library so release pipeline resource can be added.

Issue Number: #49

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [X] Yes
- [ ] No

Adding the release client library in order to keep the PRs for release pipeline as small as possible.

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

## Other information

In order to keep all PR small this is the first dependency that must be added. Release is a very large API and at least 1 future pull request will be large as it includes all of the CRUD.

### CODE REVIEW

**Comment by exocom** [comment]
@xuzhang3 Can you help me with this build failure? I've run the commands below and can not reproduce the error in the build pipeline.

```
go mod vendor
make check-vendor-vs-mod
git status --porcelain vendor
```

**Comment by xuzhang3** [comment]
Hi @exocom  You need update the vendor folder with `go mod vendor` and `go mod tidy`. I don't have the permissions to push code to your branch.
image

**Comment by exocom** [comment]
@xuzhang3 removed the vendor directory. Ran both commands. committed and pushed and same build error.
Also I've added you as a collaborator to my repo so I believe you can push to it.

How did you get to the window in the screenshot?

The test passes when I run it locally. I'm on:
 OSX 10.14.6 

I also used the Docker container and got the exact same results.

go version go1.12.17 darwin/amd64
image

**Comment by xuzhang3** [comment]
@exocom  This issues was caused by line separator. The update files in vendor are encoded with `LF` while the dependency files are encode with `CRLF`.

**Comment by xuzhang3** [comment]
Hi @exocom  you can update your local git config with: `git config --global core.autocrlf true`. [reference document](https://stackoverflow.com/questions/35503036/git-and-intellij-lines-separator-issue)

**Review by xuzhang3 — APPROVED** [review]

**Comment by xuzhang3** [comment]
LGTM

**Comment by exocom** [comment]
@xuzhang3 Thank you! I was totally stumped.

**Pull request merged**
