### PR TITLE
fix: flatten project falls back to organization default template ID

### LINKED ISSUE #199: Error parsing Work Item Template ID, got : invalid UUID length: 0
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and Azure DevOps Provider) Version

```
PS /Users/timja/projects/hmcts/ops-bootstrap/Terraform/Environments/Sandbox> terraform -v
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azuread v0.11.0
+ provider registry.terraform.io/hashicorp/azurerm v2.15.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/terraform-providers/azuredevops v0.0.1

Your version of Terraform is out of date! The latest version
is 0.13.4. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* `data.azuredevops_project`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

```
data "azuredevops_project" "project" {
  project_name = "DevOps"
}
```

### Debug Output

can't see anything useful there

### Expected Behavior

data source works

### Actual Behavior

```
Error: Error flattening project: Error parsing Work Item Template ID, got : invalid UUID length: 0

  on ../../Modules/Infrastructure/Management/main.tf line 323, in data "azuredevops_project" "project":
 323: data "azuredevops_project" "project" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This project wasn't created by AzureDevOps, looks like it's expecting something to be setup that isn't.

### References

* #0000

### PR DESCRIPTION
**Pull request by wwmoraes**
The Azure DevOps API does not guarantee a process template ID will be returned when getting a project detail. This seems to be caused for projects which use the organisation default template. As such, the lookup logic should allow to fallback to that value, if none is present at the project level.

The changes introduced allow an empty work item template parameter, which will force a lookup on the organisation level. The default value is kept as `Agile` for compatibility and design choices.

Fixes #199

## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran lint checks locally prior to submission.
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Issue Number:

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [x] No

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

### CODE REVIEW

**Comment by xuzhang3** [comment]
@wwmoraes  this issue is still not fixed,  fallback to ORG default template may set the wrong template result in a state `diff`.

**Comment by wwmoraes** [comment]
> @wwmoraes this issue is still not fixed, fallback to ORG default template may set the wrong template result in a state `diff`.

Thank you @xuzhang3 for the review! I've updated the code to remove the hardcoded `Agile` template and instead use the organisation default. This means a breaking change for a subset of existing customers that both:

* don't set `work_item_template` explicitly on their resources
* have a work item template set on their organisation different than `Agile`

This also has the side-effect that future changes on the organisation default template will cause all resources without `work_item_template` explicitly set to trigger a recreation. For such cases, the best practice is to set it.

**Comment by xuzhang3** [comment]
@wwmoraes  I do not think change the default value to empty string and set it to the default organization process template is the best choice 
1. The default value will be changed via the organization default process template.
2. The default is not clear to users, it will set to the default process template of the organization,  not the empty string defined in the schema.
3. Breaking changes. The template cannot be found, this could be a permission issue not the APIs, though this fix can be a workaround for this issue.

**Comment by wwmoraes** [comment]
@xuzhang3 thank you again for reviewing it 😄 

> The default value will be changed via the organization default process template.

This is exactly how the upstream service works: the organization itself has a default. Having a custom hardcoded value here means this provider has a distinct behaviour than the upstream service, which increases cognitive load. Mitigating an eventual recreation diff seems like a poor reason to do that. Besides, infrastructure-as-code is meant to be declarative, so a customer is prone to uncontrolled changes for things they do not explicitly configure, which seems fair.

> The default is not clear to users, it will set to the default process template of the organization, not the empty string defined in the schema.

I've updated the docs mentioning that the default is the one set on the organization. The empty string on the schema is due to the "offline" approach used for its creation. We could change the schema during initialization using the configure context function, but that wouldn't solve the declared empty string you're referring to.

If you mean the upstream service documentation is unclear about this then that's a problem of the upstream service provider.

> Breaking changes. The template cannot be found, this could be a permission issue not the APIs, though this fix can be a workaround for this issue.

If you mean the original issue, #199, then its not a permission issue: one of the users that tested it is the organization owner.

**Comment by xuzhang3** [comment]
@wwmoraes  thanks for your feedback, I would like to keep the default type to `Agile` not set it to empty string and fall back to organization default template. Keep it clear and visible to users when run `terraform plan`. Agree with fall back to organization  default template when template not found.

**Comment by wwmoraes** [comment]
@xuzhang3 would you be so kind as to review it again? I've reinstated the `Agile` default value, and configured an empty string to trigger the organisation fallback. 😄

**Review by xuzhang3 — APPROVED** [review]

**Comment by xuzhang3** [comment]
@wwmoraes LGTM 🚢

**Pull request merged**
