### PR TITLE
Add azuredevops_variable_group_permissions & azuredevops_library_permissions

### PR DESCRIPTION
**Pull request by davidcorrigan714**
## All Submissions:

* [ x ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ x ] I have updated the documentation accordingly.
* [ x ] I have added tests to cover my changes.
* [ x ] All new and existing tests passed.
* [ x ] My code follows the code style of this project.
* [ x ] I ran lint checks locally prior to submission.
* [ x ] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Adding the azuredevops_library_permissions and azuredevops_variable_group_permissions resources 'cause we needed them and have been using these in our fork.

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [ x ] No

## Does this introduce a breaking change?

- [ ] Yes
- [ x ] No

## Notes
Somewhat related to #280 for the library permissions. I didn't add Secure Files, iirc I couldn't find the API calls to manage secure files which means there'd be no acceptance tests for managing their permissions.

### CODE REVIEW

**Comment by rdalbuquerque** [comment]
This would be a great addition :)

**Comment by dominikhuembeli** [comment]
Hi, this would be realy great to have.

**Comment by ajmclaug1** [comment]
I've been testing this and it works like a dream. It's something we find really useful, is there anything holding it back from being merged into the main release?

**Comment by tceduard** [comment]
any chance we can get this in ? & if so what would it take to do so?

**Comment by tceduard** [comment]
@xuzhang3 just a gentle nudge to see how can we get this in...

**Review by xuzhang3 — APPROVED** [review]

**Comment by xuzhang3** [comment]
```log
=== RUN   TestAccLibraryPermissions_SetPermissions
--- PASS: TestAccLibraryPermissions_SetPermissions (107.61s)
=== RUN   TestAccLibraryPermissions_UpdatePermissions
--- PASS: TestAccLibraryPermissions_UpdatePermissions (110.92s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests        226.723s


=== RUN   TestAccVariableGroupPermissions_SetPermissions
--- PASS: TestAccVariableGroupPermissions_SetPermissions (97.84s)
=== RUN   TestAccVariableGroupPermissions_UpdatePermissions
--- PASS: TestAccVariableGroupPermissions_UpdatePermissions (118.04s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests        241.094s

```

**Pull request merged**
