### PR TITLE
feat/`r_servicehook_permissions`

### PR DESCRIPTION
**Pull request by tmeckel**
## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran lint checks locally prior to submission.
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

This pull requersts adds the `azuredevops_servicehook_permissions` resource 

Issue Numbers: 

* Closes #505 

image

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [x] No

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

### CODE REVIEW

**Review by xuzhang3 — CHANGES_REQUESTED** [review]
@tmeckel LGTM,  a few change requested, `website/docs/r/servicehook_permissions.html.markdown` should add to  https://github.com/microsoft/terraform-provider-azuredevops/blob/main/website/azuredevops.erb

**Comment by tmeckel** [comment]
@xuzhang3 I added the missing entry to `azuredevops.erb`. @martenvd created a PR for this resource as well #505 I'd would like to have more people contributing to the provider, so I'd like to see his PR merged instead of mine. Although he's missing the same documentation like inside `azuredevops.erb`. 😁  It's up to you which one you prefer.

image

**Comment by martenvd** [comment]
@tmeckel, thank you for the opportunity, I have updated the `azuredevops.erb` now as well.

**Comment by xuzhang3** [comment]
@tmeckel I will keep this PR opened until @martenvd 's PR merged or you can close by yourself.

**Comment by tmeckel** [comment]
@xuzhang3 I'll close my PR when @martenvd PR is merged 👍🏼

**Pull request closed without merging**
