### PR TITLE
add bitbucket support

### PR DESCRIPTION
**Pull request by jonasbark**
## All Submissions:
-------------------------------------
* [YES] Have you added an explanation of what your changes do and why you'd like us to include them?
* [NO] I have updated the documentation accordingly.
* [NO] I have added tests to cover my changes.
* [NA] All new and existing tests passed.
* [YES] My code follows the code style of this project.
* [YES] I ran lint checks locally prior to submission.
* [YES] Have you checked to ensure there aren't other open PRs for the same update/change?

## What is the current behavior?
-------------------------------------
Only Github and Vstfs is currently whitelisted. There's no way to add a Bitbucket repository.

Issue Number: https://github.com/microsoft/terraform-provider-azuredevops/issues/219

## What is the new behavior?
-------------------------------------
This PR adds Bitbucket to the whitelisted repository types. I tried it and it works just fine.

## Does this introduce a breaking change?
-------------------------------------
- [NO]

### CODE REVIEW

**Comment by jonasbark** [comment]
I added additional tests!

**Comment by nmiodice** [comment]
Playing with this locally and finding that you need a referenced `service_connection_id` for the build to actually run. I'm adding some validation locally to see if I can get this implemented today.

Also, I'm going to add some acceptance tests in addition to the unit tests that you have written. These will actually attempt to configure a bitbucket build. I'll have more later today :)

**Comment by nmiodice** [comment]
Hmm... So I'm not sure the best way to get the changes into this branch :). Here is what I did:

```
# Follow github instructions to checkout changes locally
git fetch origin refs/pull/260/head
git checkout -b feilfeilundfeil/feature/bitbucket FETCH_HEAD

# make changes...

# commit changes
git add -A && git commit -m"..."
```

But there is no upstream branch for me to push into. I have a `patch.git` file that can be applied (and am happy to share it here), but I'm not sure if there is a better way to commit to your remote branch. Any ideas?

**Comment by nmiodice** [comment]
@jonasbark I just found how easy it is to upload the patch directly to git. Here it is. Can you download this and run the following to your branch, then re-push?

`git apply patch.txt`

[patch.txt](https://github.com/microsoft/terraform-provider-azuredevops/files/4462127/patch.txt)

**Comment by jonasbark** [comment]
I just did - thank you!

**Comment by nmiodice** [comment]
Looks like the failure was transient -- i've re-run the CI. One last thing that you'll need to do is update your branch off of the latest master, otherwise I cannot merge.

**Comment by nmiodice** [comment]
Hmm, possibly not transient. I'll look into this more today or tomorrow when I have a free minute but today is a little busy with my other project

**Comment by nmiodice** [comment]
@jonasbark Are you able to rebase off of master? For some reason, GitHub will not allow me to do it on your behalf. The issue that broke your build was due to a bad timeout condition that occurred occasionally. It has since been merged into master.

**Comment by nmiodice** [comment]
@jonasbark Are you able to rebase off of master? For some reason, GitHub will not allow me to do it on your behalf. The issue that broke your build was due to a bad timeout condition that occurred occasionally. It has since been merged into master.

**Comment by nmiodice** [comment]
@jonasbark Are you able to rebase off of master? For some reason, GitHub will not allow me to do it on your behalf. The issue that broke your build was due to a bad timeout condition that occurred occasionally. It has since been merged into master.

**Comment by jonasbark** [comment]
Done!

**Comment by nmiodice** [comment]
Sorry for the close, I had intended to merge this... Sorry!

**Comment by nmiodice** [comment]
Do you mind doing one final rebase and I'll get this in. Apologies.

**Comment by jonasbark** [comment]
Don't worry, I'm happy to help!

**Comment by nmiodice** [comment]
@jonasbark the unit tests are now failing with the following error:

```
=== RUN   TestAzureDevOpsBuildDefinition_ValidatesServiceConnection_Bitbucket
--- FAIL: TestAzureDevOpsBuildDefinition_ValidatesServiceConnection_Bitbucket (0.00s)
panic: interface conversion: interface {} is []interface {}, not *schema.Set [recovered]
	panic: interface conversion: interface {} is []interface {}, not *schema.Set [recovered]
	panic: interface conversion: interface {} is []interface {}, not *schema.Set
```

**Comment by jonasbark** [comment]
@nmiodice that was introduced by your patch :) But as the commit message had my name in it - I felt obligated to fix it aaaand I think I did

**Comment by nmiodice** [comment]
Sorry @jonasbark, for some reason it won't let me make edits on your PR. In other cases, I am usually happy to fix these as they come.

The issue you are seeing should be fixed by https://github.com/microsoft/terraform-provider-azuredevops/pull/278 but I wanted to get yours merged before we merge the timeout fix (since I've asked you a few times to rebase already)

**Comment by nmiodice** [comment]
I'll re-run your build one more time. If it still fails, I'm going to merge in the fix but you'll likely have to update your branch. Again, I'm not sure why GitHub won't let me do that for you >.<

**Comment by nmiodice** [comment]
@jonasbar you'll need to update off of master one last time

**Comment by jonasbark** [comment]
@nmiodice looks good!

**Pull request merged**
