### PR TITLE
Update .sh file execution permission

### PR DESCRIPTION
**Pull request by xuzhang3**
## All Submissions:
-------------------------------------
* [YES/NO] Have you added an explanation of what your changes do and why you'd like us to include them?
* [YES/NO] I have updated the documentation accordingly.
* [YES/NO/NA] I have added tests to cover my changes.
* [YES/NO/NA] All new and existing tests passed.
* [YES/NO/NA] My code follows the code style of this project.
* [YES/NO/NA] I ran lint checks locally prior to submission.
* [YES/NO] Have you checked to ensure there aren't other open PRs for the same update/change?

## What is the current behavior?
-------------------------------------

Issue Number: #259 

## What is the new behavior?
-------------------------------------

-
-
-

## Does this introduce a breaking change?
-------------------------------------
- [YES/NO]

## Any relevant logs, error output, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

## Other information
-------------------------------------

### CODE REVIEW

**Comment by xuzhang3** [comment]
> Did you set the executable bit for every *.sh file?

all *.sh files under scripts folder. 
```shell
git update-index --chmod=+x ./*
```

**Comment by nmiodice** [comment]
+1, can we attempt @tmeckel's suggestion before comitting?

**Comment by tmeckel** [comment]
@xuzhang3 I checked what scripts aren't executable right and what changes are displayed by Git when all scripts are tagged as executable. To avoid further errors related to the scripts, I would recommend to mark all scripts as executable and to add the additional changes to the pull request.

image

**Comment by EliiseS** [comment]
@tmeckle It might be a bit faster if you make a new PR with those changes. Could you also remove my workaround from the devcontainer? :)

**Comment by xuzhang3** [comment]
> @xuzhang3 I checked what scripts aren't executable right and what changes are displayed by Git when all scripts are tagged as executable. To avoid further errors related to the scripts, I would recommend to mark all scripts as executable and to add the additional changes to the pull request.
> 
> image

@tmeckel After branch merged,  these four .sh files should have executable permissions. You can checkout this branch to test wether permissions have been properly granted.
image

**Comment by tmeckel** [comment]
@xuzhang3 I checked out the PR on my local system and the executable permissions are set correctly now
image

**Comment by xuzhang3** [comment]
> Would be great, as already mentioned, if you could remove the `chmod +x scripts/gofmtcheck.sh` from the Dockerfile. And for consistency reasons the YAML definition for the AzDO pipeline should be cleaned up as well.
> 
> https://github.com/microsoft/terraform-provider-azuredevops/blob/e753f7b70e63d74e7c1639140e53f78cd4a7e7af/.azdo/ci.yml#L38



> Would be great, as already mentioned, if you could remove the `chmod +x scripts/gofmtcheck.sh` from the Dockerfile. And for consistency reasons the YAML definition for the AzDO pipeline should be cleaned up as well.
> 
> https://github.com/microsoft/terraform-provider-azuredevops/blob/e753f7b70e63d74e7c1639140e53f78cd4a7e7af/.azdo/ci.yml#L38

All `chmod +x` operation are removed.

**Pull request merged**
