### PR TITLE
Fix create build definition with Github failed 

### PR DESCRIPTION
**Pull request by xuzhang3**
## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran lint checks locally prior to submission.
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Issue Number: #72 #65 

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [x] No

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

## Other information
I can't create acceptance test for this scenario:
1.  The test case need a real GitHub service connection and real repository,  this will bind the test case to a specific  GitHub PAT and repository.
2. Mock test won't send the real request to GitHub, can't be used to verify the request. The request is verify by service side.

[Community post](https://developercommunity.visualstudio.com/content/problem/1109420/cannot-create-build-definition-for-github.html)

### CODE REVIEW

**Comment by siftercoder2** [comment]
I could not find a release where this change has been incorporated. currently, we are forking this repo and creating our own releases. please update releases after 0.0.1.

**Comment by xuzhang3** [comment]
@iojas  Sorry for the in inconvenience , we are blocked by the GPG signing key. The next version will be in late October.

**Comment by EliiseS** [comment]
@xuzhang3 What's a GPG signing key?

**Comment by xuzhang3** [comment]
@EliiseS  GPG key is used to signing the released ADO provider binary package. You can get the details in this document: https://www.terraform.io/docs/registry/providers/publishing.html

**Comment by siftercoder2** [comment]
@xuzhang3 no worries. Just wondering what approaches others are using to get around this.

**Comment by essic** [comment]
Hello @iojas,

I have the same issue. Did you find a work around, around this ?

**Comment by xuzhang3** [comment]
@essic Are you using  v0.0.1?  You can build a  new binary from the master branch by yourself or you can wait our next release v0.0.2.

**Pull request merged**
