### PR TITLE
New resource 'azuredevops_serviceendpoint_sonarqube'

### PR DESCRIPTION
**Pull request by tiwood**
This introduces a new resource to manage `Sonarqube Service Endpoints`.

```hcl
resource "azuredevops_serviceendpoint_sonarqube" "serviceendpoint" {
  project_id            = azuredevops_project.project.id
  url                   = "https://my-sonarqube-instance.com"
  token                 = "my-sonarqube-token"
  service_endpoint_name = "test-sonarqube"
  description           = "test"
}
```

## All Submissions:

* [X] Have you added an explanation of what your changes do and why you'd like us to include them?
* [X] I have updated the documentation accordingly.
* [X] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [X] My code follows the code style of this project.
* [X] I ran lint checks locally prior to submission.
* [X] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

New resource `azuredevops_servicendpoint_sonarqube`

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [X] No

## Does this introduce a breaking change?

- [ ] Yes
- [X] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

### CODE REVIEW

**Comment by tiwood** [comment]
@nmiodice, @xuzhang3 are tests currently expected to fail?

**Comment by xuzhang3** [comment]
Hi @exocom , is this PR still in progress?  The `soanqube` is added without any acceptance  tests.

**Comment by tmeckel** [comment]
> 
> 
> Hi @exocom , is this PR still in progress? The `soanqube` is added without any acceptance tests.

@xuzhang3 Acceptance tests would only be feasible, if you provide a Sonarqube server installation. I'm not sure if the `azuredevops_serviceendpoint_sonarqube` resource can be used with SonarCloud as well. In that case, acceptance tests could be implemented much easier, because no Sonarqube server installation would be required. @tiwood should be able to answer the last question though.

**Comment by xuzhang3** [comment]
> > Hi @exocom , is this PR still in progress? The `soanqube` is added without any acceptance tests.
> 
> @xuzhang3 Acceptance tests would only be feasible, if you provide a Sonarqube server installation. I'm not sure if the `azuredevops_serviceendpoint_sonarqube` resource can be used with SonarCloud as well. In that case, acceptance tests could be implemented much easier, because no Sonarqube server installation would be required. @tiwood should be able to answer the last question though.

@tmeckel I did some test manually, the new feature works good. @tiwood  Is the PR ready for review?

**Comment by tiwood** [comment]
@xuzhang3, I've added acceptance tests for the new resource:
```shell
=== RUN   TestAccServiceEndpointSonarqube_CreateAndUpdate
--- PASS: TestAccServiceEndpointSonarqube_CreateAndUpdate (11.03s)
```

The PR is ready for review.

**Comment by EliiseS** [comment]
@tiwood, we have migrate this repository to terraform-provider here: https://github.com/terraform-providers/terraform-provider-azuredevops. Could you resubmit your PR to the there?

I'll be closing this PR here.

**Pull request closed without merging**
