### PR TITLE
Add support for other git service connections

### LINKED ISSUE #180: Support Other Git service connections
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azuredevops_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

### PR DESCRIPTION
**Pull request by paulbehrisch**
@curiousbug and implemented support for other git service connections.

It can be used in this way

```
resource "azuredevops_serviceendpoint_other_git" "myOtherGitServiceConnection" {
  project_id            = azuredevops_project.project.id
  username              = "git_user"
  password              = "git_pass"
  service_endpoint_name = "myOtherGitServiceConnection1"
  description           = "myOtherGitServiceConnection1"
  url                   = "https://code.mygitserver.net/scm/foobar/my-repo.git"
}
```

We still have to add tests.

### CODE REVIEW

**Comment by xuzhang3** [comment]
Hi @paulbehrisch   Thanks for your contribution,   you need add some other documents and test cases.
1. Add a document  on how to use this resource. [Azure RM service conneciton document](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/website/docs/r/serviceendpoint_azurerm.html.markdown) 
2. Acceptance tests. [AzureRM ACCTests](https://github.com/microsoft/terraform-provider-azuredevops/blob/master/azuredevops/internal/acceptancetests/resource_serviceendpoint_azurerm_test.go)

**Comment by anikm1987** [comment]
Hi,
Great work. happy to see this pr request.

I am looking forward for this merge to happen. will this work with enterprise github as well?

**Comment by xuzhang3** [comment]
> Hi,
> Great work. happy to see this pr request.
> 
> I am looking forward for this merge to happen. will this work with enterprise github as well?

I think this resource will not support enterprise github. We need add a new resource `enterprise_github` to support enterprise github. [GitHub Enterprise Server service connection](https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops&tabs=yaml#sep-githubent)

**Comment by tmeckel** [comment]
Can we rename the resource to `azuredevops_serviceendpoint_git`? `azuredevops_serviceendpoint_other_git` sounds a bit awkward 😎😊

**Comment by paulbehrisch** [comment]
@tmeckel While the name is not great, it IS the official name for the connection type.

Screen Shot 2020-10-21 at 09 19 37

**Comment by tmeckel** [comment]
@paulbehrisch At first I think we don't have to adopt the poor naming of the service connection in the portal and secondly the intention of the naming in the portal is to signal that the service connection is for a plain (generic, other) Git repository and not for those hosted by GitHub for example. So I think `azuredevops_serviceendpoint_git` describes a service connection to a (generic) Git repository very well and it fits pretty good with the existing `azuredevops_serviceendpoint_github` resource.

@xuzhang3 any thoughts on this?

**Comment by xuzhang3** [comment]
@tmeckel  Agree with your idea. Personally I prefer `azuredevops_serviceendpoint_external_git`, because this service connection is used to connect other git server repos.

**Comment by tmeckel** [comment]
@xuzhang3 can you elaborate why the resource should be named `external_git`. Aren't all service connections implicitly _external_  compared to Azure DevOps? Especially because there is (currently) no way to add an _internal_ service connection to another Git repository hosted in Azure DevOps as I can see.

**Comment by xuzhang3** [comment]
@tmeckel  My understanding is that regardless of Azure DevOps or GitHub or other third party git services, this service connection can be used to connect to any Git repository. `GitHub` and `GitHub enterprise` are the specific service connections.  `Other Git` can be regarded as a generic service connection and `GitHub, GitHub enterprise` can regarded as a specific implementation.  Looks like `generic_git` is a better choice. 😄 
 
## Test `Other Git` with Azure DevOps repo :
  Repo uname/pwd and url:
image
   Other git service configure:
image
    Pipeline Config:
 User service connection in pipeline
image

**Comment by tmeckel** [comment]
@xuzhang3 `azuredevops_serviceendpoint_generic_git` sounds good 😀 👍

**Comment by xuzhang3** [comment]
@paulbehrisch Can you help add the acceptance tests for the new resource and solve the branch conflict?

**Comment by tmeckel** [comment]
@paulbehrisch after the provider has been upgraded to the v6 API, the code for service connections has to be changed. So it might be a better approach to finish the PR here before the upgrade is done.

**Comment by tmeckel** [comment]
@xuzhang3 we already have a resource `azuredevops_serviceendpoint_generic_git` in `azuredevops/internal/service/serviceendpoint/resource_serviceendpoint_generic_git.go`. Is this PR obsolete?

**Pull request closed without merging**
