### PR TITLE
feat: Multi-value data source groups

### LINKED ISSUE #483: Data source for groups
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a data source for referencing existing users but not existing groups. The only data source is for referencing a single group which throws an exception if the group is not found.

I am using json data to refer to users and groups from which I want to configure things like permissions. This currently is difficult because there is no clean way to find matches between json data and groups.

### New or Affected Resource(s)

New: data azuredevops_groups

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

### PR DESCRIPTION
**Pull request by tmeckel**
## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran lint checks locally prior to submission.
* [x]  Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

This Pull Request implements a multi-value data source for groups `azuredevops_groups` to fetch existing groups inside a project or inside a organization.

Issue Number: #483 

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [x] No

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

N/A

## Other information

Closes: #483

### CODE REVIEW

**Comment by tmeckel** [comment]
@xuzhang3 ready for review

**Comment by tmeckel** [comment]
@xuzhang3 Updated code according to PR #486

**Comment by xuzhang3** [comment]
```log
==> Checking that code complies with gofmt requirements...
==> Sourcing .env file if avaliable
if [ -f .env ]; then set -o allexport; . ./.env; set +o allexport; fi; \
        TF_ACC=1 go test -tags "all" $(go list ./azuredevops/internal/acceptancetests |grep -v 'vendor') -v -run=TestAccGroupsDataSource -timeout 120m
=== RUN   TestAccGroupsDataSource_Read_Project
=== PAUSE TestAccGroupsDataSource_Read_Project
=== RUN   TestAccGroupsDataSource_Read_NoProject
=== PAUSE TestAccGroupsDataSource_Read_NoProject
=== CONT  TestAccGroupsDataSource_Read_Project
=== CONT  TestAccGroupsDataSource_Read_NoProject
--- PASS: TestAccGroupsDataSource_Read_NoProject (6.86s)
--- PASS: TestAccGroupsDataSource_Read_Project (126.43s)
PASS
ok      github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests        127.260s

```

**Comment by xuzhang3** [comment]
LGTM

**Pull request merged**
