### PR TITLE
Improved test framework

### PR DESCRIPTION
**Pull request by tmeckel**
## All Submissions:

* [YES] Have you added an explanation of what your changes do and why you'd like us to include them?
* [YES] I have updated the documentation accordingly.
* [NA] I have added tests to cover my changes.
* [YES] All new and existing tests passed.
* [YES] My code follows the code style of this project.
* [NA] I ran lint checks locally prior to submission.
* [YES] Have you checked to ensure there aren't other open PRs for the same update/change?

## What is the current behavior?

Currently the provided `_test.go` and the associated shell scripts `unittest.sh`and `acctest.sh` do not provide a way to selectively run specific tests or a group  of tests. All defined unit or acceptance tests must be run at once.

## What is the new behavior?

This PR contains changes to implement a testing procedure to separate and group tests by using GO build tags or build constraints. ([GO build constraints](https://golang.org/pkg/go/build/#hdr-Build_Constraints)). With this approach it's possible to selectively run specific unit or acceptance tests, a group of tests, or all tests at once.

By applying GO build tag to `_test.go` files and an extension to the `unittest.sh`and `acctest.sh` it is possible to selectively run tests as described [above](#what-is-the-current-behavior)

**Example:** running all tests

```bash
$ ./scripts/unittest.sh
```

or

```bash
$ ./scripts/unittest.sh all
```

**Example:** running only test for the project resource

```bash
$ ./scripts/unittest.sh resource_project
```

Details how to author tests with this new testing approach are set out in the updated `testing.md` documentation.

## Does this introduce a breaking change?

- [YES]

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

NA

### CODE REVIEW

**Comment by tmeckel** [comment]
Hi @nmiodice  ... the build pipeline failed again. Can you gimme a hints what's wrong this time? I bet it's another formatting problem. 😁

**Comment by exocom** [comment]
@tmeckel Yes it is failing due to linting. To check the linting run `./scripts/lint-check-go.sh` in your terminal.

Here is the current output from linting:
```bash
[INFO] Linting Go Files... If this fails, run 'golint ./...' to see errors
azuredevops/utils/testhelper/hcl.go:8:1: exported function TestAccAzureGitRepoResource should have comment or be unexported
azuredevops/utils/testhelper/hcl.go:22:1: comment on exported function TestAccGroupDataSource should be of the form "TestAccGroupDataSource ..."
azuredevops/utils/testhelper/hcl.go:46:1: comment on exported function TestAccUserEntitlementResource should be of the form "TestAccUserEntitlementResource ..."
azuredevops/utils/testhelper/hcl.go:55:1: comment on exported function TestAccServiceEndpointGitHubResource should be of the form "TestAccServiceEndpointGitHubResource ..."
azuredevops/utils/testhelper/hcl.go:68:1: comment on exported function TestAccServiceEndpointDockerHubResource should be of the form "TestAccServiceEndpointDockerHubResource ..."
azuredevops/utils/testhelper/hcl.go:80:1: comment on exported function TestAccVariableGroupResource should be of the form "TestAccVariableGroupResource ..."
azuredevops/utils/testhelper/hcl.go:108:1: comment on exported function TestAccAgentPoolResource should be of the form "TestAccAgentPoolResource ..."
azuredevops/utils/testhelper/hcl.go:118:1: comment on exported function TestAccBuildDefinitionResource should be of the form "TestAccBuildDefinitionResource ..."
azuredevops/utils/testhelper/hcl.go:139:1: comment on exported function TestAccGroupMembershipResource should be of the form "TestAccGroupMembershipResource ..."
azuredevops/utils/testhelper/hcl.go:151:1: comment on exported function TestAccGroupMembershipDependencies should be of the form "TestAccGroupMembershipDependencies ..."
azuredevops/utils/testhelper/provider.go:27:1: comment on exported const TestAccResourcePrefix should be of the form "TestAccResourcePrefix ..."
Found 11 lint suggestions; failing.
```

**Comment by tmeckel** [comment]
@exocom thanks for the update :smiley:

**Comment by tmeckel** [comment]
@exocom @nmiodice Fixed all left over formatting an linting errors ... The PR is ready for review.

**Pull request merged**
