### PR TITLE
`azuredevops_securityrole_definitions`, `azuredevops_securityrole_assignment` - New resource and data source for securityrole assignments

### PR DESCRIPTION
**Pull request by favoretti**
## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran lint checks locally prior to submission.
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Issue Number:

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [x] No

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

## Any relevant logs, error output, etc?

(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

## Other information

New resource: `azuredevops_securityrole_assignment`
New datasource: `azuredevops_securityrole_definitions`

### CODE REVIEW

**Comment by xuzhang3** [comment]
@favoretti  Vendor files are typically managed by the `go mod` and may be updated, which may remove clients you have added. You can add the new client to https://github.com/microsoft/terraform-provider-azuredevops/tree/main/azuredevops/utils

**Comment by favoretti** [comment]
> @favoretti Vendor files are typically managed by the `go mod` and may be updated, which may remove clients you have added. You can add the new client to https://github.com/microsoft/terraform-provider-azuredevops/tree/main/azuredevops/utils

Ah, would that work if I put the client in locally? I mean I know it will work, asking from process/policy-wise :) Or is there an option to actually generate it in the v7 api sdk? If not, I'll drop it in utils.

**Comment by favoretti** [comment]
@xuzhang3 if local client is ok with you - then this is ready for review/merge. Thanks!

**Comment by favoretti** [comment]
@xuzhang3 ping? :)

**Comment by xuzhang3** [comment]
> ? If not, I'll drop it in utils. 

@favoretti Best practice is drop the clients to the utils for now :). And can you add the AccTests for the new added resources

**Comment by favoretti** [comment]
@xuzhang3 sure, just the mocked part? Sorry, didn't get the full hang of this provider's test suite yet :) Mostly active in azurerm world..

**Comment by xuzhang3** [comment]
> @xuzhang3 sure, just the mocked part? Sorry, didn't get the full hang of this provider's test suite yet :) Mostly active in azurerm world..

Same like azurerm. All new resource/data resource need add the AccTests.

**Comment by favoretti** [comment]
> > @xuzhang3 sure, just the mocked part? Sorry, didn't get the full hang of this provider's test suite yet :) Mostly active in azurerm world..
> 
> Same like azurerm. All new resource/data resource need add the AccTests.

Do you have any info on how I can generate a client mock from the hand-made client? Writing it by hand seems... tedious :) Thanks a lot!

**Comment by xuzhang3** [comment]
@favoretti  maybe https://github.com/microsoft/terraform-provider-azuredevops/blob/main/scripts/generate-mocks.sh?

**Comment by favoretti** [comment]
@xuzhang3 made an attempt at tests, please review.

**Comment by favoretti** [comment]
@xuzhang3 ping? :)

**Comment by xuzhang3** [comment]
@favoretti  No AccTest for the new resources, we need these test to ensure the resource working as expect

**Comment by favoretti** [comment]
@xuzhang3 what do you mean? I added tests for the resource, same as others, I think I used pipeline checks as an example.

**Comment by xuzhang3** [comment]
`azuredevops/internal/service/securityroles/resource_securityrole_assignment_test.go`  is the unit test not AccTest.  AccTest will create real resources and run a full life cycle of Terraform command(`plan -> apply -> plan -> destroy` etc.). 

More details: [Acctest](https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests)


> @xuzhang3 what do you mean? I added tests for the resource, same as others, I think I used pipeline checks as an example.

`azuredevops/internal/service/securityroles/resource_securityrole_assignment_test.go`  is the unit test not AccTest.  AccTest will create real resources and run a full life cycle of Terraform command(`plan -> apply -> plan -> destroy` etc.). 

More details: [Acctest](https://developer.hashicorp.com/terraform/plugin/sdkv2/testing/acceptance-tests)

**Comment by favoretti** [comment]
@xuzhang3 added acceptance tests, please review.

**Comment by favoretti** [comment]
```
make testacc TESTARGS='-run=TestAccAzureDevOpsSecurityroles_DataSource_Securityrole_Definitions'
==> Checking that code complies with gofmt requirements...
==> Sourcing .env file if available
if [ -f .env ]; then set -o allexport; . ./.env; set +o allexport; fi; \
	TF_ACC=1 go test -tags "all" $(go list ./azuredevops/internal/acceptancetests |grep -v 'vendor') -v -run=TestAccAzureDevOpsSecurityroles_DataSource_Securityrole_Definitions -timeout 120m
=== RUN   TestAccAzureDevOpsSecurityroles_DataSource_Securityrole_Definitions
=== PAUSE TestAccAzureDevOpsSecurityroles_DataSource_Securityrole_Definitions
=== CONT  TestAccAzureDevOpsSecurityroles_DataSource_Securityrole_Definitions
--- PASS: TestAccAzureDevOpsSecurityroles_DataSource_Securityrole_Definitions (3.21s)
PASS
ok  	github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests	3.546s 

microsoft/terraform-provider-azuredevops git:(favoretti/securityroleassignments) make testacc TESTARGS='-run=TestAccSecurityroleAssignmentResource_Basic'
==> Checking that code complies with gofmt requirements...
==> Sourcing .env file if available
if [ -f .env ]; then set -o allexport; . ./.env; set +o allexport; fi; \
	TF_ACC=1 go test -tags "all" $(go list ./azuredevops/internal/acceptancetests |grep -v 'vendor') -v -run=TestAccSecurityroleAssignmentResource_Basic -timeout 120m
=== RUN   TestAccSecurityroleAssignmentResource_Basic
=== PAUSE TestAccSecurityroleAssignmentResource_Basic
=== CONT  TestAccSecurityroleAssignmentResource_Basic
--- PASS: TestAccSecurityroleAssignmentResource_Basic (33.72s)
PASS
ok  	github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests	34.080s
```

**Comment by xuzhang3** [comment]
@favoretti  AccTest failed:
```log
=== CONT  TestAccSecurityroleAssignmentResource_Basic
    resource_securityrole_assignment_test.go:19: Step 1/1 error: Error running apply: exit status 1

        Error: invalid UUID length: 142

          with azuredevops_securityrole_assignment.test,
          on terraform_plugin_test.tf line 22, in resource "azuredevops_securityrole_assignment" "test":
          22: resource "azuredevops_securityrole_assignment" "test" {

```

**Comment by favoretti** [comment]
@xuzhang3 This is weird... That error is something I was getting before the last commit, the test consistently succeeds on my end now. You sure that run you have wasn't based off an earlier commit?
```
make testacc TESTARGS='-run=TestAccSecurityroleAssignmentResource_Basic -count=1'
==> Checking that code complies with gofmt requirements...
==> Sourcing .env file if available
if [ -f .env ]; then set -o allexport; . ./.env; set +o allexport; fi; \
	TF_ACC=1 go test -tags "all" $(go list ./azuredevops/internal/acceptancetests |grep -v 'vendor') -v -run=TestAccSecurityroleAssignmentResource_Basic -count=1 -timeout 120m
=== RUN   TestAccSecurityroleAssignmentResource_Basic
=== PAUSE TestAccSecurityroleAssignmentResource_Basic
=== CONT  TestAccSecurityroleAssignmentResource_Basic
--- PASS: TestAccSecurityroleAssignmentResource_Basic (37.64s)
PASS
ok  	github.com/microsoft/terraform-provider-azuredevops/azuredevops/internal/acceptancetests	38.019s
```

**Comment by xuzhang3** [comment]
@favoretti Not sure why the latest code not check out. Recreated the local branch from remote and tests passed.

**Review by xuzhang3 — APPROVED** [review]
LGTM

**Pull request merged**
