### PR TITLE
feat: add a new resource azuredevops_environment_resource_kubernetes

### PR DESCRIPTION
**Pull request by croemmich**
## All Submissions:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] I have updated the documentation accordingly.
* [x] I have added tests to cover my changes.
* [x] All new and existing tests passed.
* [x] My code follows the code style of this project.
* [x] I ran lint checks locally prior to submission.
* [x] Have you checked to ensure there aren't other open PRs for the same update/change?

## What about the current behavior has changed?

Added the ability to manage Kubernetes environment resources.

Introduced a new TaskAgentKubernetesResourceClient that provides a re-implementation of the taskagent.AddKubernetesResource method to allow passing the serviceEndpointId parameter, which is required by the API but cannot be passed via the official SDK implementation.

I've created microsoft/azure-devops-go-api#116 to track the issue with the official SDK.

## Does this introduce a change to `go.mod`, `go.sum` or `vendor/`?

- [ ] Yes
- [x] No

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by xuzhang3** [comment]
@croemmich   if this PR not ready, you can change it to draft.

**Comment by croemmich** [comment]
@xuzhang3, I've updated this PR with a new client implementation that allows for adding a Kubernetes environment resource against an existing serviceEndpointId. Let me know what you think. I don't have high hopes microsoft/azure-devops-go-api#116 will be resolved very quickly.

**Comment by croemmich** [comment]
Hi @xuzhang3, anything you need from me to get this merged? Thanks!

**Comment by xuzhang3** [comment]
@croemmich I prefer SDK fix this bug then we merge this PR.  Private client is a workaround  but not our best choice.

**Comment by venkatesh-thatham** [comment]
@croemmich, @xuzhang3 any update on this PR, we really need this enhancement to be merged for our use case also. Appreciate your help.

**Comment by xuzhang3** [comment]
> @croemmich, @xuzhang3 any update on this PR, we really need this enhancement to be merged for our use case also. Appreciate your help.

This PR is blocked by SDK. SDK issue: https://github.com/microsoft/azure-devops-go-api/issues/116

**Comment by croemmich** [comment]
@thatham, unfortunately I'm not a Microsoft employee so I've no levers to pull. This was contributed this 5 months ago and there's still no progress.

@xuzhang3, this isn't totally blocked, you didn't want my custom taskagentkubernetesresource client, which I get, however as far as I'm concerned the SDK is dead... it's not been touched since Jan 26, and calling it supported before that was dubious at best. This terraform provider is 100x more important to us than the SDK. If this were my project I'd certainly not get hung up on relativity easy to fix SDK limitations/bugs.

**Comment by xuzhang3** [comment]
@croemmich @thatham Sorry for the delay response.  Office SDK will be our first choice if this SDK still available otherwise I'd like to generate a private SDK based on the [swagger](https://github.com/MicrosoftDocs/vsts-rest-api-specs) instead of fix the bug out of SDK and included as local file, . I know that there are many APIs not documented or the swagger definition is not correct. 

Private SDK  used in AzureRM: https://github.com/hashicorp/terraform-provider-azurerm/tree/main/internal/services/disks/sdk

**Comment by venkatesh-thatham** [comment]
@xuzhang3, do you have any estimated date of the corresponding fix to be merged in official SDK? @croemmich, kindly advise will this private SDK will help rollout your enhancements.
I'm very desperate to get this changes.

**Comment by xuzhang3** [comment]
@thatham sorry I do not have the timeline, latest info I got is v7.1 will be released around Otc. ping @nechvatalp

**Comment by venkatesh-thatham** [comment]
@nechvatalp any update on this PR, we really need this enhancement to be merged for our use case also. Appreciate your help.

**Comment by xuzhang3** [comment]
@croemmich  can you help rebase the code to the lates and move  the SDK patch `azdosdk/taskagentkubernetesresource/client.go` etc. to resource folder `azuredevops/internal/service/taskagent/sdk`?

**Comment by rdalbuquerque** [comment]
@croemmich I got it working without the private client on v7 of SDK, I Also merged back changes from upstream. I opened a PR to your branch, source of this PR. :)

**Comment by rdalbuquerque** [comment]
> @croemmich I got it working without the private client on v7 of SDK, I Also merged back changes from upstream. I opened a PR to your branch, source of this PR. :)

@xuzhang3 should I open a new PR since haven't heard back from @croemmich ?

It's been almost a year since he last responded here :(

**Comment by SDohle** [comment]
I vote for a new PR, @rdalbuquerque. 
I'm really missing this feature.

**Comment by SDohle** [comment]
Hi @rdalbuquerque ,

please notice https://github.com/microsoft/terraform-provider-azuredevops/issues/584#issuecomment-1832434857 
Do you have plans to contribute your work as a new pull request?

**Comment by rdalbuquerque** [comment]
> Hi @rdalbuquerque ,
> 
> please notice [#584 (comment)](https://github.com/microsoft/terraform-provider-azuredevops/issues/584#issuecomment-1832434857) Do you have plans to contribute your work as a new pull request?

Sorry for the delayed response
I'll open a new PR

**Pull request merged**
