### PR TITLE
Git repo list

### PR DESCRIPTION
**Pull request by cicorias**
## All Submissions:
-------------------------------------
* [YES/NO] Have you added an explanation of what your changes do and why you'd like us to include them?
* [YES/NO] I have updated the documentation accordingly.
* [YES/NO/NA] I have added tests to cover my changes.
* [YES/NO/NA] All new and existing tests passed.
* [YES/NO/NA] My code follows the code style of this project.
* [YES/NO/NA] I ran lint checks locally prior to submission.
* [YES/NO] Have you checked to ensure there aren't other open PRs for the same update/change?

## What is the current behavior?
-------------------------------------

Issue Number: N/A

## What is the new behavior?
-------------------------------------

-
-
-

## Does this introduce a breaking change?
-------------------------------------
- [YES/NO]

## Any relevant logs, error output, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

## Other information
-------------------------------------

### CODE REVIEW

**Comment by nmiodice** [comment]
@cicorias will you be working on this or should I close?

**Comment by cicorias** [comment]
@nmiodice hold off till brew year as I have finals, yes I do go to school..

**Comment by tmeckel** [comment]
@cicorias will you continue work on this? In a project where we already use the provider, we noticed that we needed this feature. So it would be great if you could continue work on this :grin: 

Copy @tiwood  for reference

**Comment by cicorias** [comment]
i'll give a better update by this weekend. I just started a LOA and probably if I focus on this one have it done shortly..

So, in other words, I'll give you an update on IF i can get to this in a day or two.

**Comment by tmeckel** [comment]
@cicorias any update on this?

**Comment by cicorias** [comment]
unfortunately, I'm now on extended leave so I won't be able to address this for some time.

**Comment by tmeckel** [comment]
@cicorias okay, thanks for the info. Would you mind retract (close) the pull request? I'd like to implement this functionality because we have a demand for it in a current customer project. My proposal would be to start with the code in your branch `cicorias:git-repo-list` by merging it into my own new branch so won't lose your credit on your work.

**Comment by tmeckel** [comment]
@cicorias as said I imported your work into a new branch on our development repository.
https://github.com/tiwood/terraform-provider-azuredevops/tree/d_git_repositories

I will make sure that you will get credit when I file the PR.

**Pull request closed without merging**
