### PR TITLE
[azuredevops_serviceendpoint_azurerm] subscriptionName + subscriptionId have to start with a lower-case 's'

### PR DESCRIPTION
**Pull request by tiwood**
## All Submissions:
-------------------------------------
* [YES/NO] Have you added an explanation of what your changes do and why you'd like us to include them? Yes
* [YES/NO] I have updated the documentation accordingly. Yes
* [YES/NO/NA] I have added tests to cover my changes. Yes
* [YES/NO/NA] All new and existing tests passed. NA
* [YES/NO/NA] My code follows the code style of this project. Yes
* [YES/NO/NA] I ran lint checks locally prior to submission. Yes
* [YES/NO] Have you checked to ensure there aren't other open PRs for the same update/change? Yes

## What is the current behavior?
-------------------------------------
Issue Number: #294 

## What is the new behavior?
-------------------------------------

AzureRM Service Connection can be used to link Azure Key Vaults to a variable group.

## Does this introduce a breaking change?
-------------------------------------
- NO

### CODE REVIEW

**Comment by tiwood** [comment]
This fixes #294

**Comment by nmiodice** [comment]
This fixes a few issues in the unit tests for this resource. Here is one example. You can re-run using `./scripts/unittest.sh`

```
2020-05-06T12:06:02.9449517Z --- FAIL: TestAzureDevOpsServiceEndpointAzureRM_ExpandFlatten_Roundtrip (0.00s)
2020-05-06T12:06:02.9449925Z     require.go:157: 
2020-05-06T12:06:02.9450300Z         	Error Trace:	resource_serviceendpoint_azurerm_test.go:66
2020-05-06T12:06:02.9450714Z         	Error:      	Not equal: 
2020-05-06T12:06:02.9452369Z         	            	expected: serviceendpoint.ServiceEndpoint{AdministratorsGroup:(*webapi.IdentityRef)(nil), Authorization:(*serviceendpoint.EndpointAuthorization)(0x21f6ed0), CreatedBy:(*webapi.IdentityRef)(nil), Data:(*map[string]string)(0x220d680), Description:(*string)(0xc000046970), GroupScopeId:(*uuid.UUID)(nil), Id:(*uuid.UUID)(0x2230120), IsReady:(*bool)(nil), IsShared:(*bool)(nil), Name:(*string)(0xc000046960), OperationStatus:interface {}(nil), Owner:(*string)(0xc000046980), ReadersGroup:(*webapi.IdentityRef)(nil), Type:(*string)(0xc000046990), Url:(*string)(0xc0000469a0)}
2020-05-06T12:06:02.9455491Z         	            	actual  : serviceendpoint.ServiceEndpoint{AdministratorsGroup:(*webapi.IdentityRef)(nil), Authorization:(*serviceendpoint.EndpointAuthorization)(0xc0001a01f0), CreatedBy:(*webapi.IdentityRef)(nil), Data:(*map[string]string)(0xc0000acfb8), Description:(*string)(0xc0001a0110), GroupScopeId:(*uuid.UUID)(nil), Id:(*uuid.UUID)(0xc0000a85c0), IsReady:(*bool)(nil), IsShared:(*bool)(nil), Name:(*string)(0xc0001a00d0), OperationStatus:interface {}(nil), Owner:(*string)(0xc0001a0100), ReadersGroup:(*webapi.IdentityRef)(nil), Type:(*string)(0xc0001a0220), Url:(*string)(0xc0001a0230)}
2020-05-06T12:06:02.9457137Z         	            	
2020-05-06T12:06:02.9457406Z         	            	Diff:
2020-05-06T12:06:02.9457991Z         	            	--- Expected
2020-05-06T12:06:02.9458348Z         	            	+++ Actual
2020-05-06T12:06:02.9458887Z         	            	@@ -17,4 +17,4 @@
2020-05-06T12:06:02.9459354Z         	            	   (string) (len=10) "scopeLevel": (string) (len=12) "Subscription",
2020-05-06T12:06:02.9460313Z         	            	-  (string) (len=14) "subscriptionId": (string) (len=36) "42125daf-72fd-417c-9ea7-080690625ad3",
2020-05-06T12:06:02.9461259Z         	            	-  (string) (len=16) "subscriptionName": (string) (len=17) "SUBSCRIPTION_TEST"
2020-05-06T12:06:02.9461844Z         	            	+  (string) (len=14) "subscriptionId": (string) "",
2020-05-06T12:06:02.9462365Z         	            	+  (string) (len=16) "subscriptionName": (string) ""
2020-05-06T12:06:02.9462748Z         	            	  }),

```

**Comment by nmiodice** [comment]
FYI, the code here will likely need to be updated after we merge https://github.com/microsoft/terraform-provider-azuredevops/pull/277

**Comment by logachev** [comment]
This was actually fixed in my PR: https://github.com/microsoft/terraform-provider-azuredevops/pull/277/files#diff-df13dba2c93f6f816c377309ef578fa2R81

It is really unfortunate that DevOps API is case-sensitive.. @nmiodice can we follow up with them?

**Comment by nmiodice** [comment]
@logachev we should add it as a feedback item internally.

@tiwood can you review the PR mentioned by @logachev to confirm that this is indeed a duplicate? If so, we can close this out.

**Pull request closed without merging**
